# Generated by Django 2.2.5 on 2019-11-09 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gradesApp', '0004_auto_20191109_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds', models.IntegerField()),
                ('dld', models.IntegerField()),
                ('dm', models.IntegerField()),
                ('la', models.IntegerField()),
                ('stud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradesApp.Student')),
            ],
        ),
    ]
