# Generated by Django 2.2.5 on 2019-11-09 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradesApp', '0005_marks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Marks',
            new_name='Grade',
        ),
    ]
