# Generated by Django 2.2.5 on 2019-11-10 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradesApp', '0006_auto_20191109_1503'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
